apiVersion: v1
kind: Service
metadata:
  name: mywebapp  # This will be modified to kustom-mywebapp-v1 by Kustomize
spec:
  selector:
    app: mywebapp  # This selector must match the labels in the Pod
  ports:
  - port: 80
    protocol: TCP
    name: flask
  type: NodePort
