name: CI Build and Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dockerhub_user/repo:pr-${{ github.event.number }}

      - name: Update Kubernetes manifests
        run: |
          sed -i "s|image: .*|image: dockerhub_user/repo:pr-${{ github.event.number }}|g" k8s/deployment.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to pr-${{ github.event.number }}"
          git push origin main
